version: '3.8'
name: awsgoo
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy # https://github.com/nginx-proxy/nginx-proxy
    ports:
      - "9889:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - blog
      # - blog-a
      # - blog-b
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 50M
        reservations:
          cpus: '0.05'
          memory: 30M

# blog-a:
# build: blog-a/
# blog-b:
# build: blog-b/
# - VIRTUAL_HOST=google.aws.com,google.google.com
# - VIRTUAL_HOST=jelly.google.com


  blog:
    image: taengguu/auto-lb:0.1.0
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '0.05'
          memory: 50M
        reservations:
          cpus: '0.01'
          memory: 20M
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=aws.google.com
      - VIRTUAL_PORT=80

